// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbtv5h8txgC-YearIzdOQ3NJ1Mu8q5Asc',
    appId: '1:687955727091:web:48e903f6e2c836fab59d86',
    messagingSenderId: '687955727091',
    projectId: 'flutter-notificaciones-cfaf9',
    authDomain: 'flutter-notificaciones-cfaf9.firebaseapp.com',
    storageBucket: 'flutter-notificaciones-cfaf9.appspot.com',
    measurementId: 'G-YFPLQME119',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGvbDexUb9uu1HUz1PR8O67Sxm-8FQnQ',
    appId: '1:687955727091:android:923caf1155ab49aeb59d86',
    messagingSenderId: '687955727091',
    projectId: 'flutter-notificaciones-cfaf9',
    storageBucket: 'flutter-notificaciones-cfaf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGWbAY_R_3KF7jB_tPe4Q0a4bvVSNTgA',
    appId: '1:687955727091:ios:6c40e434b8644c25b59d86',
    messagingSenderId: '687955727091',
    projectId: 'flutter-notificaciones-cfaf9',
    storageBucket: 'flutter-notificaciones-cfaf9.appspot.com',
    iosClientId: '687955727091-r91tmvahfsgmofi4i465llvhgtikahpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBGWbAY_R_3KF7jB_tPe4Q0a4bvVSNTgA',
    appId: '1:687955727091:ios:3128e796cc79cce4b59d86',
    messagingSenderId: '687955727091',
    projectId: 'flutter-notificaciones-cfaf9',
    storageBucket: 'flutter-notificaciones-cfaf9.appspot.com',
    iosClientId: '687955727091-79qve31fe2t0stvlo2pofrph9cgoks6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationsProject.RunnerTests',
  );
}
